import type { BackupEnvelope } from './models.js';
import { BACKUP_FORMAT_VERSION, SCHEMA_VERSION } from './versions.js';
import { validateBackupEnvelope } from './validation.js';

export const MAX_BACKUP_BYTES = 32 * 1024 * 1024;
export function canonicalBackupWithoutChecksum(value: Omit<BackupEnvelope, 'checksum'>): string { return JSON.stringify(value, Object.keys(value).sort()); }
export async function sha256Hex(text: string): Promise<string> { const bytes = new TextEncoder().encode(text); const digest = await crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(digest)].map((v) => v.toString(16).padStart(2, '0')).join(''); }
export async function createBackupEnvelope(value: Omit<BackupEnvelope, 'checksum'>): Promise<BackupEnvelope> { const envelope = { ...value, checksum: await sha256Hex(canonicalBackupWithoutChecksum(value)) }; const encoded = new TextEncoder().encode(JSON.stringify(envelope)); if (encoded.length > MAX_BACKUP_BYTES) throw new Error('Backup exceeds the 32 MiB safety limit.'); return envelope; }
export async function validateAndParseBackup(input: string | Uint8Array): Promise<BackupEnvelope> { const bytes = typeof input === 'string' ? new TextEncoder().encode(input) : input; if (bytes.length > MAX_BACKUP_BYTES) throw new Error('Backup exceeds the 32 MiB safety limit.'); let parsed: unknown; try { parsed = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes)); } catch { throw new Error('Backup is not valid UTF-8 JSON.'); } const valid = validateBackupEnvelope(parsed); if (!valid.valid) throw new Error(`Backup validation failed: ${valid.errors[0]?.message ?? 'invalid envelope'}`); const envelope = valid.value; if (envelope.formatVersion !== BACKUP_FORMAT_VERSION || envelope.schemaVersion > SCHEMA_VERSION) throw new Error('Backup format is newer than this reader.'); const { checksum, ...rest } = envelope; if (await sha256Hex(canonicalBackupWithoutChecksum(rest)) !== checksum) throw new Error('Backup checksum does not match.'); return envelope; }
